Jojo144/compteur_du_gase

README.md
base/admin.py
base/forms.py
base/models.py
base/static/base/base.css
base/static/base/select2-bootstrap4.css
base/templates/admin/recurring.html
base/templates/base/activity_board.html
base/templates/base/base.html
compteur/settings.py
requirements.txt

Rend le tableau des perms super sympa

---

base/templates/base/approslist.html
base/templates/base/compteslist.html
base/templates/base/purchaseslist.html
base/templates/base/subscriptionslist.html

Sinon c'est un peu embêtant si on s'en sert pour la compta.

Affiche 2 décimales pour les totaux monétaires dans les vues de stats

---

scripts/backup
scripts/restore

Pas testé les backups pour voir si ça fonctionne pour autant, mais ça ne peut
qu'y aider.
Ref #32

[ynh] Corrige les warnings/erreurs triviales sur le backup/restore

---

README.md
base/admin.py
compteur/settings.py
compteur/urls.py
manifest.json
scripts/install
ynh_auth/apps.py
ynh_auth/auth.py
ynh_auth/middleware.py
ynh_auth/urls.py
ynh_auth/views.py

(sinon tu voudrais pas me donner accès à ta branche en écriture ? :p)

Quelques pas de plus entre le POC et un truc propre :)

---

README.md

Address #49 
Je vais envoyer un mail à ceux que je connais pour avoir leur accord ...

Liste asso + orthographe README

---

base/templates/base/members.html

Correct sorting members

---

base/exports.py

Faisait de mauvais regroupements car on comparait des dates UTC avec des dates
localisées (subtil). Par exemple en faisant un inventaire entre 23h et minuit
il n'était pas comptabilisé sur le bon jour (et donc probablement pas
comptabilisé du tout dans les totaux).

Corrige l'agrégat des inventaires par jour

---

base/templates/base/approslist.html
base/templates/base/compteslist.html
base/templates/base/purchaseslist.html
base/templates/base/subscriptionslist.html

Le compteur avait implémenté la fin des temps pour le 12/12/2020.
Fix #46

Corrige le filtrage par année

---

base/templates/base/approslist.html
base/templates/base/compteslist.html
base/templates/base/purchaseslist.html
base/templates/base/stockslist.html
base/templates/base/subscriptionslist.html

Faudrait quand même factoriser un peu tout ces codes de listings :x.
Fix #17

Affiche les centimes dans les totaux de listing -> seulement mini refactoring

---

base/static/base/base.css
base/templates/base/achats.html

Et diminue de 50% ma frustration en permanence :-)

Faite en sorte que le bouton « dans panier » reste toujours visible

---

base/static/base/base.css
base/templates/base/achats.html

50% du reste de ma frustration disparaît.

Ajoute des raccourcis clavier au panier

---

base/templates/base/achats.html

(désolé pour le diff touffu, mais voilà ce qui arrive avec du code pas
très bien indenté :p)
Fix #67

Corrige le bug de recherche qui fait se tromper de produit

---

base/templates/base/achats.html

Rétablit la possibilité de saisir des courses négatives

---

compteur/settings.py
requirements.txt

Le diff est surprenament petit mais j'ai tout testé ce que j'ai pu, je n'ai même pas déclenché d'autre warning :-o.

Met à jour les dépendances (dont Django en 3.2)

---

base/templates/base/products.html

J'en ai profité pour faire plusieurs petites corrections.

Fix  #71 tri tableau des produits

---

base/views.py

Corrige une erreur 500 à l'approvisionement

---

base/models.py
base/views.py

Corrige réception non historisée à réception de commande

---

base/views.py

Corrige un plantage à l'affichage du panier lorsque produit sans catégorie

---

base/admin.py

Permet de programmer toutes les 2 semaines

---

base/templates/base/achats.html
base/templates/base/appro.html
base/templates/base/compte.html

- Vue panier
- Vue appro de compte
- Vue réception de commande
Fix #87
cc @Jojo144

Fix #87  Corrige la double soumission au double-clic sur quelques vues

---

base/templates/base/stats.html

Amélioration des graphes de stats de produit
